micronaut:
    application:
        name: terminal-api
    server:
      port: 8086
    security:
      enabled: true
      token:
        jwt:
          enabled: true
          signatures:
            secret:
              generator:
                secret: <secret_key>
                base64: true
                jws-algorithm: HS512
endpoints:
    all:
        path: /mis/api/er/terminal
datasources:
    default:
        url: <db_url>
        username: <db_user>
        password: <db_pass>
        driverClassName: org.postgresql.Driver
external-services:
    er:
        url: http://localhost:8090
    patient:
        url: http://localhost:8080
    dictionary:
        url: http://localhost:8100
